name: build
on:
  workflow_call:
    inputs:
      build_type:
        description: 'Build type'
        required: false
        type: string
        default: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Phaka uses itself to build and configure itself
      - name: Bootstrap
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}} 
          cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}} 
          sudo cmake --install ${{github.workspace}}/build --config ${{inputs.build_type}} 
          rm -Rf ${{github.workspace}}/build
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      # Verify that the bootstrap worked
      - name: Bootstrap Verification
        run: phaka --version

      # Let's do the real build
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}} --install-prefix ${{github.workspace}}/dist
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{inputs.build_type}} --verbose
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --config ${{inputs.build_type}} --verbose
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Package
        working-directory: ${{github.workspace}}/build
        run:  cpack --config CPackConfig.cmake -C ${{inputs.build_type}} --verbose
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ${{github.workspace}}/build/artifacts/*